$axure.loadCurrentPage({
  "url":"pdf_detailed_view.html",
  "generationDate":new Date(1425466561345.26),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"7bc2db273e8848fd9e91be65b54cbcd5",
    "type":"Axure:Page",
    "name":"pdf detailed view",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"77740c8d2a6646b89cd46f3959198791",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f9b3bbeb04ef4e79ac3df98f721a0887"},
{
          "id":"fdae7ef7719d4859bc8dd48cd9f54070",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "selected":{
}},
            "location":{
              "x":-2,
              "y":215},
            "size":{
              "width":270,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"37ccb12ed4674726bd0a152615f80047",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "selected":{
}},
                "location":{
                  "x":-2,
                  "y":215},
                "size":{
                  "width":270,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open DownloadInventory in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"downloadinventory.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/downloadinventory/u45.png",
            "mouseOver~":"images/downloadinventory/u45_mouseOver.png"}},
{
          "id":"8b5dcae0fc834a31a7ffe82c9ddf2d57",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":65,
              "y":235},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9e9e2accfa7d4903b8bc286c04236b4d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":65,
                  "y":235},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open DownloadInventory in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"downloadinventory.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ae17410a3b444d2290fa8b6e4c8d07d9",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":0,
              "y":270},
            "size":{
              "width":268,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b70cdcc722a14f5d9ead62ce22ac900d",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":268,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaign Report in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaign_report.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/downloadinventory/u49.png",
            "mouseOver~":"images/downloadinventory/u49_mouseOver.png"}},
{
          "id":"1ed83ece20eb4f448fbd7b41b926e41f",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":64,
              "y":286},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e09b1ec1c844492f8e313387189706ba",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":64,
                  "y":286},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaign Report in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaign_report.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"6b0c4ac862754496a5bed51c4c7fee2b",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "mouseDown":{
},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":268,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"e4f6daca30cf4f118bc1c5d8fa438fe3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "mouseDown":{
},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":268,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaignwise Media in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaignwise_media.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/downloadinventory/u49.png",
            "selected~":"images/downloadinventory/u49_mouseOver.png",
            "mouseOver~":"images/downloadinventory/u49_mouseOver.png"}},
{
          "id":"042453b03c344ffe95c73de8fa0e3b2d",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":64,
              "y":337},
            "size":{
              "width":136,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6e124ec2e6184524a51b9770d00c27c3",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":64,
                  "y":337},
                "size":{
                  "width":136,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaignwise Media in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaignwise_media.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"ef1af173aee64ae6bdcd111323318f77",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":317},
            "size":{
              "width":268,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/downloadinventory/u57_line.png"}},
{
          "id":"db188ae9e33841ceb2d56cab700153d7",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":265},
            "size":{
              "width":268,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/downloadinventory/u57_line.png"}},
{
          "id":"1761a924c78246868e4a0b7ca063ecc2",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":140},
            "size":{
              "width":590,
              "height":835},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"9dc948a2a0dd47b1a24803f37727bb96",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":140},
                "size":{
                  "width":590,
                  "height":835},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pdf_detailed_view/u17.png"}},
{
          "id":"c6c0e81083044c05acdc3ef84c101054",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":143},
            "size":{
              "width":588,
              "height":832},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb49b82b517b45bcbc8a963a7935de9e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":143},
                "size":{
                  "width":588,
                  "height":832},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pdf_detailed_view/u19.png"}},
{
          "id":"1ea492604557451b8b394f5f5886788f",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":1043},
            "size":{
              "width":588,
              "height":832},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"5067bbbf29f84be4be46df699f48a0c0",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":1043},
                "size":{
                  "width":588,
                  "height":832},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pdf_detailed_view/u21.png"}},
{
          "id":"5379b52055bc4acd802b5fb2d3c71059",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":1042},
            "size":{
              "width":589,
              "height":833},
            "borderWidth":"2",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF000000}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4c20d94a1f6c4b6aa12f9b26cd60c60a",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":1042},
                "size":{
                  "width":589,
                  "height":833},
                "borderWidth":"2",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF000000}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/pdf_detailed_view/u23.png"}}]}},
  "masters":{
    "f9b3bbeb04ef4e79ac3df98f721a0887":{
      "packageId":"f9b3bbeb04ef4e79ac3df98f721a0887",
      "type":"Axure:Master",
      "name":"background",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f85df7b5bdb042a697dcac0592dc278d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1583,
                "height":1349}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e31b86c07d0453cabbecde611a76b11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1583,
                    "height":1349}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/downloadinventory/u1.png"}}]}}},
  "objectPaths":{
    "77740c8d2a6646b89cd46f3959198791":{
      "scriptId":"u0",
      "f85df7b5bdb042a697dcac0592dc278d":{
        "scriptId":"u1"},
      "1e31b86c07d0453cabbecde611a76b11":{
        "scriptId":"u2"}},
    "fdae7ef7719d4859bc8dd48cd9f54070":{
      "scriptId":"u3"},
    "37ccb12ed4674726bd0a152615f80047":{
      "scriptId":"u4"},
    "8b5dcae0fc834a31a7ffe82c9ddf2d57":{
      "scriptId":"u5"},
    "9e9e2accfa7d4903b8bc286c04236b4d":{
      "scriptId":"u6"},
    "ae17410a3b444d2290fa8b6e4c8d07d9":{
      "scriptId":"u7"},
    "b70cdcc722a14f5d9ead62ce22ac900d":{
      "scriptId":"u8"},
    "1ed83ece20eb4f448fbd7b41b926e41f":{
      "scriptId":"u9"},
    "e09b1ec1c844492f8e313387189706ba":{
      "scriptId":"u10"},
    "6b0c4ac862754496a5bed51c4c7fee2b":{
      "scriptId":"u11"},
    "e4f6daca30cf4f118bc1c5d8fa438fe3":{
      "scriptId":"u12"},
    "042453b03c344ffe95c73de8fa0e3b2d":{
      "scriptId":"u13"},
    "6e124ec2e6184524a51b9770d00c27c3":{
      "scriptId":"u14"},
    "ef1af173aee64ae6bdcd111323318f77":{
      "scriptId":"u15"},
    "db188ae9e33841ceb2d56cab700153d7":{
      "scriptId":"u16"},
    "1761a924c78246868e4a0b7ca063ecc2":{
      "scriptId":"u17"},
    "9dc948a2a0dd47b1a24803f37727bb96":{
      "scriptId":"u18"},
    "c6c0e81083044c05acdc3ef84c101054":{
      "scriptId":"u19"},
    "fb49b82b517b45bcbc8a963a7935de9e":{
      "scriptId":"u20"},
    "1ea492604557451b8b394f5f5886788f":{
      "scriptId":"u21"},
    "5067bbbf29f84be4be46df699f48a0c0":{
      "scriptId":"u22"},
    "5379b52055bc4acd802b5fb2d3c71059":{
      "scriptId":"u23"},
    "4c20d94a1f6c4b6aa12f9b26cd60c60a":{
      "scriptId":"u24"}}});