$axure.loadCurrentPage({
  "url":"downloadpdf_detail.html",
  "generationDate":new Date(1425466558876.12),
  "isCanvasEnabled":false,
  "variables":["OnLoadVariable"],
  "page":{
    "packageId":"5ba410d1251e42e9a857314672dc2ca6",
    "type":"Axure:Page",
    "name":"downloadPDF detail",
    "notes":{
},
    "style":{
      "baseStyle":"627587b6038d43cca051c114ac41ad32",
      "pageAlignment":"near",
      "fill":{
        "fillType":"solid",
        "color":0xFFFFFFFF},
      "image":null,
      "imageHorizontalAlignment":"near",
      "imageVerticalAlignment":"near",
      "imageRepeat":"auto",
      "favicon":null,
      "sketchFactor":"0",
      "colorStyle":"appliedColor",
      "fontName":"Applied Font",
      "borderWidth":"0"},
    "adaptiveStyles":{
},
    "interactionMap":{
},
    "diagram":{
      "objects":[{
          "id":"bf45a451aa43459c957d977b1880bbd0",
          "label":"",
          "type":"referenceDiagramObject",
          "styleType":"referenceDiagramObject",
          "visible":true,
          "style":{
},
          "adaptiveStyles":{
},
          "masterId":"f9b3bbeb04ef4e79ac3df98f721a0887"},
{
          "id":"dc192da9dfcd4aa8be37be63ef1b0a29",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "selected":{
}},
            "location":{
              "x":-2,
              "y":215},
            "size":{
              "width":270,
              "height":55},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"6345feb35ea34a82a60c3d5a0b3de4dd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "selected":{
}},
                "location":{
                  "x":-2,
                  "y":215},
                "size":{
                  "width":270,
                  "height":55},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open DownloadInventory in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"downloadinventory.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/downloadinventory/u45.png",
            "mouseOver~":"images/downloadinventory/u45_mouseOver.png"}},
{
          "id":"550657f6cbfa492aa4bb94d8364107b1",
          "label":"",
          "type":"buttonShape",
          "styleType":"h1",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":65,
              "y":235},
            "size":{
              "width":125,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"41728fe8d9c6418db20939851fb5a288",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":65,
                  "y":235},
                "size":{
                  "width":125,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open DownloadInventory in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"downloadinventory.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"f476962663de4a1c8bc71dd03b80f0d8",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":0,
              "y":270},
            "size":{
              "width":268,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"fb4915fdd7cc4d1aa4ffe11b55c533c9",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":0,
                  "y":270},
                "size":{
                  "width":268,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaign Report in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaign_report.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/downloadinventory/u49.png",
            "mouseOver~":"images/downloadinventory/u49_mouseOver.png"}},
{
          "id":"f792b72547314a8da22956917d48ec0a",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":64,
              "y":286},
            "size":{
              "width":116,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"991e6b0d655c4db48181fd54f2c02ea4",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":64,
                  "y":286},
                "size":{
                  "width":116,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaign Report in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaign_report.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"a7e30d1ed76f468495867425a0543322",
          "label":"",
          "type":"buttonShape",
          "styleType":"buttonShape",
          "visible":true,
          "style":{
            "stateStyles":{
              "mouseOver":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}},
              "mouseDown":{
},
              "selected":{
                "fill":{
                  "fillType":"solid",
                  "color":0xFFE4E4E4}}},
            "location":{
              "x":0,
              "y":320},
            "size":{
              "width":268,
              "height":50},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFFFFF}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b718ba6221e44f84bbdf8e0b729f0bbd",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "stateStyles":{
                  "mouseOver":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}},
                  "mouseDown":{
},
                  "selected":{
                    "fill":{
                      "fillType":"solid",
                      "color":0xFFE4E4E4}}},
                "location":{
                  "x":0,
                  "y":320},
                "size":{
                  "width":268,
                  "height":50},
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFFFFFF}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaignwise Media in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaignwise_media.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"images/downloadinventory/u49.png",
            "selected~":"images/downloadinventory/u49_mouseOver.png",
            "mouseOver~":"images/downloadinventory/u49_mouseOver.png"}},
{
          "id":"bec97d174c85460cb9807df48b38e06b",
          "label":"",
          "type":"buttonShape",
          "styleType":"h2",
          "visible":true,
          "style":{
            "fontName":"'Arial Regular', 'Arial'",
            "fontSize":"14px",
            "fontWeight":"400",
            "location":{
              "x":64,
              "y":337},
            "size":{
              "width":136,
              "height":16}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"d76c5a911f1347d0aefa8440a3864a3e",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "fontName":"'Arial Regular', 'Arial'",
                "fontSize":"14px",
                "fontWeight":"400",
                "location":{
                  "x":64,
                  "y":337},
                "size":{
                  "width":136,
                  "height":16}},
              "adaptiveStyles":{
}}],
          "interactionMap":{
            "onClick":{
              "description":"OnClick",
              "cases":[{
                  "description":"Case 1",
                  "isNewIfGroup":false,
                  "actions":[{
                      "action":"linkWindow",
                      "description":"Open Campaignwise Media in Current Window",
                      "target":{
                        "targetType":"page",
                        "url":"campaignwise_media.html",
                        "includeVariables":true},
                      "linkType":"current"}]}]}},
          "tabbable":true,
          "images":{
            "normal~":"resources/images/transparent.gif"}},
{
          "id":"b27f67ddedd542b38014d96f17838b7c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":317},
            "size":{
              "width":268,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/downloadinventory/u57_line.png"}},
{
          "id":"d8a73e338d904afab201a82a1023b52c",
          "label":"",
          "type":"horizontalLine",
          "styleType":"horizontalLine",
          "visible":true,
          "style":{
            "location":{
              "x":0,
              "y":265},
            "size":{
              "width":268,
              "height":10},
            "borderFill":{
              "fillType":"solid",
              "color":0xFFCCCCCC}},
          "adaptiveStyles":{
},
          "images":{
            "start~":"resources/images/transparent.gif",
            "end~":"resources/images/transparent.gif",
            "line~":"images/downloadinventory/u57_line.png"}},
{
          "id":"03ec964fed3a4b17be0684b60a908b2a",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":143},
            "size":{
              "width":589,
              "height":832},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"decf65b9030b4405bfc1248ceb59b971",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":143},
                "size":{
                  "width":589,
                  "height":832},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/downloadpdf_detail/u17.png"}},
{
          "id":"a6c596c8f6444dbd936901b396b17c24",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":143},
            "size":{
              "width":588,
              "height":832},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"b60eca8bab2a43e38a5599f87adba4c7",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":143},
                "size":{
                  "width":588,
                  "height":832},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/downloadpdf_detail/u19.png"}},
{
          "id":"0dafcbe6484848eabe9c8c749caa8dab",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":300,
              "y":1042},
            "size":{
              "width":585,
              "height":828},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"58b7c84eb30043a4aa311ab51547e618",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":300,
                  "y":1042},
                "size":{
                  "width":585,
                  "height":828},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/downloadpdf_detail/u21.png"}},
{
          "id":"085ccd53d3054b28961173b804762045",
          "label":"",
          "type":"imageBox",
          "styleType":"imageBox",
          "visible":true,
          "style":{
            "location":{
              "x":920,
              "y":1042},
            "size":{
              "width":585,
              "height":828},
            "borderWidth":"1",
            "borderFill":{
              "fillType":"solid",
              "color":0xFF999999}},
          "adaptiveStyles":{
},
          "objects":[{
              "id":"4bb7c604a68240039ea49965b7ee7a44",
              "label":"",
              "isContained":true,
              "type":"richTextPanel",
              "styleType":"paragraph",
              "visible":true,
              "style":{
                "location":{
                  "x":920,
                  "y":1042},
                "size":{
                  "width":585,
                  "height":828},
                "borderWidth":"1",
                "borderFill":{
                  "fillType":"solid",
                  "color":0xFF999999}},
              "adaptiveStyles":{
}}],
          "images":{
            "normal~":"images/downloadpdf_detail/u23.png"}}]}},
  "masters":{
    "f9b3bbeb04ef4e79ac3df98f721a0887":{
      "packageId":"f9b3bbeb04ef4e79ac3df98f721a0887",
      "type":"Axure:Master",
      "name":"background",
      "notes":{
},
      "style":{
        "baseStyle":"627587b6038d43cca051c114ac41ad32",
        "pageAlignment":"near",
        "fill":{
          "fillType":"solid",
          "color":0xFFFFFFFF},
        "image":null,
        "imageHorizontalAlignment":"near",
        "imageVerticalAlignment":"near",
        "imageRepeat":"auto",
        "favicon":null,
        "sketchFactor":"0",
        "colorStyle":"appliedColor",
        "fontName":"Applied Font",
        "borderWidth":"0"},
      "adaptiveStyles":{
},
      "interactionMap":{
},
      "diagram":{
        "objects":[{
            "id":"f85df7b5bdb042a697dcac0592dc278d",
            "label":"",
            "type":"imageBox",
            "styleType":"imageBox",
            "visible":true,
            "style":{
              "size":{
                "width":1583,
                "height":1349}},
            "adaptiveStyles":{
},
            "objects":[{
                "id":"1e31b86c07d0453cabbecde611a76b11",
                "label":"",
                "isContained":true,
                "type":"richTextPanel",
                "styleType":"paragraph",
                "visible":true,
                "style":{
                  "size":{
                    "width":1583,
                    "height":1349}},
                "adaptiveStyles":{
}}],
            "images":{
              "normal~":"images/downloadinventory/u1.png"}}]}}},
  "objectPaths":{
    "bf45a451aa43459c957d977b1880bbd0":{
      "scriptId":"u0",
      "f85df7b5bdb042a697dcac0592dc278d":{
        "scriptId":"u1"},
      "1e31b86c07d0453cabbecde611a76b11":{
        "scriptId":"u2"}},
    "dc192da9dfcd4aa8be37be63ef1b0a29":{
      "scriptId":"u3"},
    "6345feb35ea34a82a60c3d5a0b3de4dd":{
      "scriptId":"u4"},
    "550657f6cbfa492aa4bb94d8364107b1":{
      "scriptId":"u5"},
    "41728fe8d9c6418db20939851fb5a288":{
      "scriptId":"u6"},
    "f476962663de4a1c8bc71dd03b80f0d8":{
      "scriptId":"u7"},
    "fb4915fdd7cc4d1aa4ffe11b55c533c9":{
      "scriptId":"u8"},
    "f792b72547314a8da22956917d48ec0a":{
      "scriptId":"u9"},
    "991e6b0d655c4db48181fd54f2c02ea4":{
      "scriptId":"u10"},
    "a7e30d1ed76f468495867425a0543322":{
      "scriptId":"u11"},
    "b718ba6221e44f84bbdf8e0b729f0bbd":{
      "scriptId":"u12"},
    "bec97d174c85460cb9807df48b38e06b":{
      "scriptId":"u13"},
    "d76c5a911f1347d0aefa8440a3864a3e":{
      "scriptId":"u14"},
    "b27f67ddedd542b38014d96f17838b7c":{
      "scriptId":"u15"},
    "d8a73e338d904afab201a82a1023b52c":{
      "scriptId":"u16"},
    "03ec964fed3a4b17be0684b60a908b2a":{
      "scriptId":"u17"},
    "decf65b9030b4405bfc1248ceb59b971":{
      "scriptId":"u18"},
    "a6c596c8f6444dbd936901b396b17c24":{
      "scriptId":"u19"},
    "b60eca8bab2a43e38a5599f87adba4c7":{
      "scriptId":"u20"},
    "0dafcbe6484848eabe9c8c749caa8dab":{
      "scriptId":"u21"},
    "58b7c84eb30043a4aa311ab51547e618":{
      "scriptId":"u22"},
    "085ccd53d3054b28961173b804762045":{
      "scriptId":"u23"},
    "4bb7c604a68240039ea49965b7ee7a44":{
      "scriptId":"u24"}}});